FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.10

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com \
    && apt-get update --allow-insecure-repositories \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash